<a href="https://colab.research.google.com/github/CameronKenworthyCode/python/blob/main/project_euler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://projecteuler.net/

http://www.s-anand.net/euler.html

In [ ]:
!pip install ipdb
import ipdb
import time

#1.

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [ ]:
sum = 0
for i in range(3, 1000):
  if (i % 3 == 0) or (i % 5 == 0):
    sum += i

print(sum)

233168

#2.
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [ ]:
sum = 2
term1 = 1
term2 = 2
term3 = 3
while term3 < 4000000:
  term1 = term2
  term2 = term3
  term3 = term2 + term1
  if term3 % 2 == 0:
    sum += term3

print(sum)

4613732

In [ ]:
#save previous fib calculations in dict for fast lookup
cache = {}
def fib(n):
    #print(cache)
    cache[n] = cache.get(n, 0) or (n <= 1 and 1 or fib(n-1) + fib(n-2))
    return cache[n]

n,i = 0,0
while fib(i) <= 4000000:
    if not fib(i) % 2: n = n + fib(i)
    i = i + 1

print(n)

4613732

#3.
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [ ]:
prime = 600851475143
factor = 2
while factor * factor < prime:
  while prime % factor == 0:
    prime = prime / factor
  factor = factor + 1

print(int(prime))

6857

#4.
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [9]:
answers = []
exit = 0
for i in range(999,99, -1):
  if exit == 1:
    break
  for j in range(999,99, -1):
    if str(i*j) == str(i*j)[::-1]:
      #print('i:', i, '\nj:', j, '\nanswer:', i*j)
      answers.append(i*j)
      if len(answers) > 2:
        exit = 1
        break

print(max(answers))

906609

In [10]:
#fast method
n = 0
for a in range(999, 100, -1):
    for b in range(a, 100, -1): #only look for b > a so you don't repeat calculations
        x = a * b
        if x > n: # found a larger value
            s = str(a * b)
            if s == s[::-1]:
                n = a * b

print(n)

906609

#5.
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [8]:
#brute force

foo = 100
exit = 0

#start = time.perf_counter()

while not exit:
  foo += 20
  for i in range(1,21):
    if foo % i:
      break
    if i == 20:
      exit = 1

#end = time.perf_counter()
#print(round(end - start, 3)*10)
print(foo)

232792560

In [ ]:
def gcd(a,b):
  #print('b: ', b, 'and gcd(', b, ',', a, '%', b, ') or ', a )
  return b and gcd(b, a % b) or a
def lcm(a,b): 
  return a * b / gcd(a,b)

n = 1
for i in range(1, 21):
    n = lcm(n, i)

print(int(n))

232792560

#6
The sum of the squares of the first ten natural numbers is,
1^2 + 2^2 + ... + 10^2 = 385
The square of the sum of the first ten natural numbers is,
(1 + 2 + ... + 10)^2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 - 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [ ]:
sum_square = 0
square_sum = 0
for i in range(1, 101):
  sum_square += i**2

for i in range(1, 101):
  square_sum +=  i

print(square_sum**2 - sum_square)

25164150

#7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [26]:
def is_prime(n):
  for i in range(2, int(n**.5)+1):
    if not n % i:
      return False
  return True

n = 13
count = 6
while count < 10001:
  n += 2
  if is_prime(n):
    count += 1

print(n)

104743

#8
The four adjacent digits in the 1000-digit number that have the greatest product are 9 Ã— 9 Ã— 8 Ã— 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [ ]:
def sum_string(s):
  product = 1
  for i in range(len(s)):
    n = int(s[i])
    product *= n
  return product

s = '7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450'
sum = 0

for i in range(13, len(s) - 13):
  snip = sum_string(s[i-13: i])
  if snip > sum:
    sum = snip

print(sum)

23514624000

#9
A Pythagorean triplet is a set of three natural numbers, a  b  c, for which,
a^2 + b^2 = c^2
For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [4]:
#brute force
exit = False

for a in range(1, 1000):
  if exit:
    break
  for b in range(1, 1000-a):
      c = 1000 - (a+b)
      if b >= c:
        break
      #print( 'a:', i, 'b:', j, 'c:', k)
      if (a**2 + b**2 == c**2):
        print( 'a:', a, 'b:', b, 'c:', c, '\nAnswer:', a*b*c)
        exit = True
        break

a: 200 b: 375 c: 425
Answer: 31875000

#10
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [38]:
#brute force

def is_prime(n):
  if n == 1:
    return False
  for i in range(2, int(n**.5)+1):
    if not n % i:
      return False
  return True

sum = 2 #start with 2 because loop will skip it

for i in range(1, 2000000, 2):
  if is_prime(i):
    sum += i

print(sum)

142913828922

In [16]:
sieve = [True] * 2000000    # assume all values between 1 and 2000000 are prime

def mark(sieve, x):
    for i in range(x+x, len(sieve), x): #for each number go to each multiple of that number
        sieve[i] = False #and mark it as non-prime

for x in range(2, int(len(sieve) ** 0.5) + 1): # go through square root of the sieve
    if sieve[x]: mark(sieve, x) #mark out non-prime multiples

primes = [i for i in range(2, len(sieve)) if sieve[i]] #all remaining indexes marked true are primes
sum = 0
for i in range(len(primes)): #sum up primes
  sum += primes[i]

print(sum)

142913828922