<a href="https://colab.research.google.com/github/CameronKenworthyCode/python/blob/main/project_euler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://projecteuler.net/

http://www.s-anand.net/euler.html

In [ ]:
!pip install ipdb
import ipdb
import time

#1.

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [ ]:
sum = 0
for i in range(3, 1000):
  if (i % 3 == 0) or (i % 5 == 0):
    sum += i

print(sum)

233168

#2.
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [ ]:
sum = 2
term1 = 1
term2 = 2
term3 = 3
while term3 < 4000000:
  term1 = term2
  term2 = term3
  term3 = term2 + term1
  if term3 % 2 == 0:
    sum += term3

print(sum)

4613732

In [ ]:
#save previous fib calculations in dict for fast lookup
cache = {}
def fib(n):
    #print(cache)
    cache[n] = cache.get(n, 0) or (n <= 1 and 1 or fib(n-1) + fib(n-2))
    return cache[n]

n,i = 0,0
while fib(i) <= 4000000:
    if not fib(i) % 2: n = n + fib(i)
    i = i + 1

print(n)

4613732

#3.
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [ ]:
prime = 600851475143
factor = 2
while factor * factor < prime:
  while prime % factor == 0:
    prime = prime / factor
  factor = factor + 1

print(int(prime))

6857

#4.
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [ ]:
answers = []
exit = 0
for i in range(999,99, -1):
  if exit == 1:
    break
  for j in range(999,99, -1):
    if str(i*j) == str(i*j)[::-1]:
      #print('i:', i, '\nj:', j, '\nanswer:', i*j)
      answers.append(i*j)
      if len(answers) > 2:
        exit = 1
        break

print(max(answers))

906609

In [ ]:
#fast method
n = 0
for a in range(999, 100, -1):
    for b in range(a, 100, -1): #only look for b > a so you don't repeat calculations
        x = a * b
        if x > n: # found a larger value
            s = str(a * b)
            if s == s[::-1]:
                n = a * b

print(n)

906609

#5.
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [ ]:
#brute force

foo = 100
exit = 0

#start = time.perf_counter()

while not exit:
  foo += 20
  for i in range(1,21):
    if foo % i:
      break
    if i == 20:
      exit = 1

#end = time.perf_counter()
#print(round(end - start, 3)*10)
print(foo)

232792560

In [ ]:
def gcd(a,b):
  #print('b: ', b, 'and gcd(', b, ',', a, '%', b, ') or ', a )
  return b and gcd(b, a % b) or a
def lcm(a,b): 
  return a * b / gcd(a,b)

n = 1
for i in range(1, 21):
    n = lcm(n, i)

print(int(n))

232792560

#6
The sum of the squares of the first ten natural numbers is,
1^2 + 2^2 + ... + 10^2 = 385
The square of the sum of the first ten natural numbers is,
(1 + 2 + ... + 10)^2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 - 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [ ]:
sum_square = 0
square_sum = 0
for i in range(1, 101):
  sum_square += i**2

for i in range(1, 101):
  square_sum +=  i

print(square_sum**2 - sum_square)

25164150

#7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [ ]:
def is_prime(n):
  for i in range(2, int(n**.5)+1):
    if not n % i:
      return False
  return True

n = 13
count = 6
while count < 10001:
  n += 2
  if is_prime(n):
    count += 1

print(n)

104743

#8
The four adjacent digits in the 1000-digit number that have the greatest product are 9 Ã— 9 Ã— 8 Ã— 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [ ]:
def sum_string(s):
  product = 1
  for i in range(len(s)):
    n = int(s[i])
    product *= n
  return product

s = '7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450'
sum = 0

for i in range(13, len(s) - 13):
  snip = sum_string(s[i-13: i])
  if snip > sum:
    sum = snip

print(sum)

23514624000

#9
A Pythagorean triplet is a set of three natural numbers, a  b  c, for which,
a^2 + b^2 = c^2
For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [ ]:
#brute force
exit = False

for a in range(1, 1000):
  if exit:
    break
  for b in range(1, 1000-a):
      c = 1000 - (a+b)
      if b >= c:
        break
      #print( 'a:', i, 'b:', j, 'c:', k)
      if (a**2 + b**2 == c**2):
        print( 'a:', a, 'b:', b, 'c:', c, '\nAnswer:', a*b*c)
        exit = True
        break

a: 200 b: 375 c: 425
Answer: 31875000

#10
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [ ]:
#brute force

def is_prime(n):
  if n == 1:
    return False
  for i in range(2, int(n**.5)+1):
    if not n % i:
      return False
  return True

sum = 2 #start with 2 because loop will skip it

for i in range(1, 2000000, 2):
  if is_prime(i):
    sum += i

print(sum)

142913828922

In [ ]:
#very fast prime

sieve = [True] * 2000000    # assume all values between 1 and 2000000 are prime

def mark(sieve, x):
    for i in range(x+x, len(sieve), x): #for each number go to each multiple of that number
        sieve[i] = False #and mark it as non-prime

for x in range(2, int(len(sieve) ** 0.5) + 1): # starting values to map multiples of will be up to size sqrt(len(sieve))
    if sieve[x]: mark(sieve, x) #mark out non-prime multiples

#all remaining indexes marked true are primes
primes = [i for i in range(2, len(sieve)) if sieve[i]] #convert their index number to a value in a list 

sum = 0
for i in range(len(primes)): #sum up primes in list
  sum += primes[i]

print(sum)

142913828922

#11
In the 20Ã—20 grid below, four numbers along a diagonal line have been marked in red.

```
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

```
The product of these numbers is 26 Ã— 63 Ã— 78 Ã— 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20Ã—20 grid?

In [ ]:
#brute force

def get_adjacent(y, x, width, height):
  #return adjacent coordinates to a given coordinate
  adjacents = [[],[],[],[],[],[],[],[]]
  for i in range(0, 4):
    if y-3 < 0:
      break
    adjacents[0].append([y-i, x]) #above
  for i in range(0, 4):
    if y+3 > height-1:
      break
    adjacents[1].append([y+i, x]) #below
  for i in range(0, 4):
    if x-3 < 0:
      break
    adjacents[2].append([y, x-i]) #left 
  for i in range(0, 4):
    if x+3 > width-1:
      break
    adjacents[3].append([y, x+i]) #right
  for i in range(0,4):
    if (x+3 > width-1) or (y+3 > height-1):
        break
    adjacents[4].append([y+i,x+i]) #diagonal NE
  for i in range(0,4):
    if (x+3 > width-1) or (y-3 < 0):
        break
    adjacents[5].append([y-i,x+i]) #diagonal SE
  for i in range(0,4):
    if (x-3 < 0) or (y+3 > height-1):
        break
    adjacents[6].append([y+i,x-i]) #diagonal NW
  for i in range(0,4):
    if (x-3 < 0) or (y-3 < 0):
        break
    adjacents[7].append([y-i,x-i]) #diagonal SW
  return adjacents


block = '''08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48'''

#prep grid of numbers into 2D array
block = block.split('\n') #get rows
height = len(block)
width = len(block[0].split(' ')) #get length of rows
grid = [[]*width]*len(block) #create a grid of correct size
for i in range(len(block)): #fill the grid with each row
  row = block[i].split(' ')
  grid[i] = row

#go through grid and look at all adjacent lines to check products
top_line = []
top_line_values = [[],[],[],[]]
top_product = 0
for i in range(len(grid)): #for each row
  for j in range(len(grid[0])): #for each column
    adjacent = get_adjacent(i,j, width-1, height) 
    for k in range(len(adjacent)):
      #for each adjacent line
      product = 1
      if len(adjacent[k]) == 0: #cant go 4 that way
        continue
      for l in range(len(adjacent[k])):
        #for each coord in the adjacent
        product *= int(grid[adjacent[k][l][0]][adjacent[k][l][1]]) #multiply product
      if product > top_product:
        top_line = adjacent[k]
        top_product = product
        for l in range(len(adjacent[k])):
          top_line_values[l] = (int(grid[adjacent[k][l][0]][adjacent[k][l][1]]))

print('indexes:', top_line)
print('values:', top_line_values)
print('answer:', top_product)

indexes: [[12, 6], [13, 5], [14, 4], [15, 3]]
values: [89, 94, 97, 87]
answer: 70600674

#12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1

 
 3: 1,3
 
 6: 1,2,3,6

10: 1,2,5,10

15: 1,3,5,15

21: 1,3,7,21

28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [ ]:
def count_divisors(number):
  if number == 1:
    return 1
  count = 2 #1 and itself
  for i in range(2, int(number**.5)+1):
    if number % i == 0:
      count += 2
  return count


sum = 0
count = 0
divisors = 0
while divisors < 500:
  count += 1
  sum += count
  divisors = count_divisors(sum)

print(sum)

76576500

#13
Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

In [ ]:
string_ ='''37107287533902102798797998220837590246510135740250
46376937677490009712648124896970078050417018260538
74324986199524741059474233309513058123726617309629
91942213363574161572522430563301811072406154908250
23067588207539346171171980310421047513778063246676
89261670696623633820136378418383684178734361726757
28112879812849979408065481931592621691275889832738
44274228917432520321923589422876796487670272189318
47451445736001306439091167216856844588711603153276
70386486105843025439939619828917593665686757934951
62176457141856560629502157223196586755079324193331
64906352462741904929101432445813822663347944758178
92575867718337217661963751590579239728245598838407
58203565325359399008402633568948830189458628227828
80181199384826282014278194139940567587151170094390
35398664372827112653829987240784473053190104293586
86515506006295864861532075273371959191420517255829
71693888707715466499115593487603532921714970056938
54370070576826684624621495650076471787294438377604
53282654108756828443191190634694037855217779295145
36123272525000296071075082563815656710885258350721
45876576172410976447339110607218265236877223636045
17423706905851860660448207621209813287860733969412
81142660418086830619328460811191061556940512689692
51934325451728388641918047049293215058642563049483
62467221648435076201727918039944693004732956340691
15732444386908125794514089057706229429197107928209
55037687525678773091862540744969844508330393682126
18336384825330154686196124348767681297534375946515
80386287592878490201521685554828717201219257766954
78182833757993103614740356856449095527097864797581
16726320100436897842553539920931837441497806860984
48403098129077791799088218795327364475675590848030
87086987551392711854517078544161852424320693150332
59959406895756536782107074926966537676326235447210
69793950679652694742597709739166693763042633987085
41052684708299085211399427365734116182760315001271
65378607361501080857009149939512557028198746004375
35829035317434717326932123578154982629742552737307
94953759765105305946966067683156574377167401875275
88902802571733229619176668713819931811048770190271
25267680276078003013678680992525463401061632866526
36270218540497705585629946580636237993140746255962
24074486908231174977792365466257246923322810917141
91430288197103288597806669760892938638285025333403
34413065578016127815921815005561868836468420090470
23053081172816430487623791969842487255036638784583
11487696932154902810424020138335124462181441773470
63783299490636259666498587618221225225512486764533
67720186971698544312419572409913959008952310058822
95548255300263520781532296796249481641953868218774
76085327132285723110424803456124867697064507995236
37774242535411291684276865538926205024910326572967
23701913275725675285653248258265463092207058596522
29798860272258331913126375147341994889534765745501
18495701454879288984856827726077713721403798879715
38298203783031473527721580348144513491373226651381
34829543829199918180278916522431027392251122869539
40957953066405232632538044100059654939159879593635
29746152185502371307642255121183693803580388584903
41698116222072977186158236678424689157993532961922
62467957194401269043877107275048102390895523597457
23189706772547915061505504953922979530901129967519
86188088225875314529584099251203829009407770775672
11306739708304724483816533873502340845647058077308
82959174767140363198008187129011875491310547126581
97623331044818386269515456334926366572897563400500
42846280183517070527831839425882145521227251250327
55121603546981200581762165212827652751691296897789
32238195734329339946437501907836945765883352399886
75506164965184775180738168837861091527357929701337
62177842752192623401942399639168044983993173312731
32924185707147349566916674687634660915035914677504
99518671430235219628894890102423325116913619626622
73267460800591547471830798392868535206946944540724
76841822524674417161514036427982273348055556214818
97142617910342598647204516893989422179826088076852
87783646182799346313767754307809363333018982642090
10848802521674670883215120185883543223812876952786
71329612474782464538636993009049310363619763878039
62184073572399794223406235393808339651327408011116
66627891981488087797941876876144230030984490851411
60661826293682836764744779239180335110989069790714
85786944089552990653640447425576083659976645795096
66024396409905389607120198219976047599490197230297
64913982680032973156037120041377903785566085089252
16730939319872750275468906903707539413042652315011
94809377245048795150954100921645863754710598436791
78639167021187492431995700641917969777599028300699
15368713711936614952811305876380278410754449733078
40789923115535562561142322423255033685442488917353
44889911501440648020369068063960672322193204149535
41503128880339536053299340368006977710650566631954
81234880673210146739058568557934581403627822703280
82616570773948327592232845941706525094512325230608
22918802058777319719839450180888072429661980811197
77158542502016545090413245809786882778948721859617
72107838435069186155435662884062257473692284509516
20849603980134001723930671666823555245252804609722
53503534226472524250874054075591789781264330331690'''

numbers = []
for number in string_.split('\n'):
  numbers.append(int(number))

sum = 0
for number in numbers:
  sum += number

print(str(sum)[:10])

5537376230

#14
The following iterative sequence is defined for the set of positive integers:

n â†’ n/2 (n is even)
n â†’ 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 â†’ 40 â†’ 20 â†’ 10 â†’ 5 â†’ 16 â†’ 8 â†’ 4 â†’ 2 â†’ 1
It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

In [ ]:
#brute force

#diff = 0
start_record = 0
chain_record = 0

for i in range(999999, 0, -1):
#  if diff*10 > 999999:
#    break
  count = 1
  j = i
  while i != 1:
    count += 1
    if i % 2 == 0:
      i = i // 2
      continue
    else:
      i = 3*i + 1
  if count > chain_record:
    chain_record = count
    #diff = start_record - j
    #print(diff)
    start_record = j

print(start_record)

837799

#15
Starting in the top left corner of a 2Ã—2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20Ã—20 grid?

In [ ]:
def fact(n):
    f = 1
    for x in range(1, n+1): 
      f = f * x
    return f

# ((2n)!)/(n!*n!) gives number of paths corner to corner
# combinatorics
print(int(fact(40) / fact(20) / fact(20)))

137846528820

#16
215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2**1000?

In [ ]:
#memory hungry, converts to string

x = str(pow(2,1000))
sum = 0
for i in range(len(x)):
  sum += int(x[i])

print(sum)

1366

In [ ]:
#memory efficient, no string

def digits(n):
    s = 0
    while n > 0:
        s = s + (n % 10) #get the lowest digit
        n = n // 10 #remove the lowest digit
    return s

print(digits(pow(2,1000)))

1366

#17
If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?


NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

In [ ]:
import numpy as np

words = [
    (   1,  'one'      , ''     ),
    (   2,  'two'      , ''     ),
    (   3,  'three'    , ''     ),
    (   4,  'four'     , ''     ),
    (   5,  'five'     , ''     ),
    (   6,  'six'      , ''     ),
    (   7,  'seven'    , ''     ),
    (   8,  'eight'    , ''     ),
    (   9,  'nine'     , ''     ),
    (  10,  'ten'      , ''     ),
    (  11,  'eleven'   , ''     ),
    (  12,  'twelve'   , ''     ),
    (  13,  'thirteen' , ''     ),
    (  14,  'fourteen' , ''     ),
    (  15,  'fifteen'  , ''     ),
    (  16,  'sixteen'  , ''     ),
    (  17,  'seventeen', ''     ),
    (  18,  'eighteen' , ''     ),
    (  19,  'nineteen' , ''     ),
    (  20,  'twenty'   , ''     ),
    (  30,  'thirty'   , ''     ),
    (  40,  'forty'    , ''     ),
    (  50,  'fifty'    , ''     ),
    (  60,  'sixty'    , ''     ),
    (  70,  'seventy'  , ''     ),
    (  80,  'eighty'   , ''     ),
    (  90,  'ninety'   , ''     ),
    ( 100,  'hundred'  , 'and'  ),
    (1000,  'thousand' , 'and'  ),
]
words.reverse()

def spell(n, words):
    word = []
    
    while n > 0: #until we have divided n down to nothing

        for num in words: #go through each possible word it could be

            if num[0] <= n: #first one smaller is prefix eg 48 -> forty
                div = n // num[0] #get first words
                n = n % num[0] #get next number for next loop
                
                if num[2]: #if number number has 'and','one thousand [and] five'
                  #append short word, 32000 -> [thirty two]
                  word.append(' '.join(spell(div, words)))
                
                #append main value, 32_000 -> ['thirty', 'two'] + ['thousand']
                word.append(num[1])
                
                if num[2] and n:
                #determine you need the 'and' added since
                #there are still more numbers to pronounce
                  word.append(num[2])
                
                break #move on to next iteration
    return word

big_word = [len(word) for n in range(1, 1001) for word in spell(n, words)]
sum = 0
for i in range(len(big_word)):
  sum += big_word[i]

print(sum)

21124

#18
By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [ ]:
#brute force
#2**n-1 routes, n is height of triangle

block = '''
75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23'''

rows = block.split('\n')
map_ = []
for i in range(1, len(rows)):
  map_.append(rows[i].split(' '))

#'00000000000000' -> '11111111111111' build all paths
top_sum = 0
top_path = []
for i in range(2**(len(map_)-1)):
    #make sure the binary string has enough moves to traverse map_
    bin_path = (len(map_)-len(bin(i)[2:]))*'0' + bin(i)[2:] 
    temp_path = [0]
    temp_sum = 0

    for j in range(1,len(map_)): #build path array from binary string
      #if its a 0 go down in map_, if its a 1 go right-down in map_
      temp_path.append(temp_path[j-1]+int(bin_path[j]))
    
    for j in range(len(temp_path)): #sum the path through map_
      temp_sum += int(map_[j][temp_path[j]])
    
    if temp_sum > top_sum: #found a better path
      top_path = temp_path
      top_sum = temp_sum

print('sum:', top_sum, '\npath:', [map_[i][top_path[i]] for i in range(len(top_path))])

sum: 1074
path: ['75', '64', '82', '87', '82', '75', '73', '28', '83', '32', '91', '78', '58', '73', '93']

#19
You are given the following information, but you may prefer to do some research for yourself.

1 Jan 1900 was a Monday.

Thirty days has September,

April, June and November.

All the rest have thirty-one,

Saving February alone,

Which has twenty-eight, rain or shine.

And on leap years, twenty-nine.

A leap year occurs on any year evenly divisible by 4, but not on a century 
unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth century (1 
Jan 1901 to 31 Dec 2000)?

In [ ]:
year = 1900
month = 1
date = 1
days_passed = 0
sunday_count = 0
is_leap = (not year % 4) and (not year == 1900)

while year < 2001:
  day = (days_passed) % 7 + 1
  
  if (date == 28) and (month ==2) and (not is_leap):
    date = 1
    month += 1
    days_passed += 1
    continue
  if (date == 29) and (month == 2) and (is_leap):
    date = 1
    month += 1
    days_passed += 1
    continue    
  if (date == 30) and (month in [4, 6, 9, 11]):
    date = 1
    month += 1
    days_passed += 1
    continue
  if date == 31:
    date = 0
    month += 1
    if month == 13:
      month = 1
      year += 1

  if (date == 1) and (day == 7) and (year > 1900):
    #print('Year:', year, '| Month:', month, '| Date:', date, '| Day:', day)
    sunday_count += 1

  is_leap = (not year % 4) and (not year == 1900)
  date += 1
  days_passed += 1

print(sunday_count)

171

#20
n! means n Ã— (n âˆ’ 1) Ã— ... Ã— 3 Ã— 2 Ã— 1

For example, 10! = 10 Ã— 9 Ã— ... Ã— 3 Ã— 2 Ã— 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!

In [ ]:
product = 1

for i in range(1, 101):
  product *= i

product_str = str(product)

sum = 0
for i in range(len(product_str)):
  sum += int(product_str[i])

print(sum)

648

#21
Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
If d(a) = b and d(b) = a, where a  b, then a and b are an amicable pair and each of a and b are called amicable numbers.

For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.

Evaluate the sum of all the amicable numbers under 10000.

In [ ]:
def divisors(number):
  divisors = [1]
  if number == 1:
    return 1
  count = 2 #1 and itself
  for i in range(2, int(number**.5+1)):
    if number % i == 0:
      divisors.append(i)
      divisors.append(number // i)
  #divisors.sort()
  sum = 0
  for divisor in divisors:
    sum += divisor
  return sum

sum = 0
for i in range(10000):
  div = divisors(i)
  if divisors(div) == i:
    if div != i:
      #print(i, div)
      sum += i

print(sum)

31626

#22
Using names.txt (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 x 53 = 49714.

What is the total of all the name scores in the file?

In [ ]:
# block = [] loaded text in deleted cell

def word_value(word):
  word = word.lower()
  sum = 0
  for i in range(len(word)):
    sum += (ord(word[i]) - 96)
  
  return sum

block.sort()

sum = 0
for i in range(len(block)):
  name = block[i]
  sum += (word_value(name)*(i+1))

print(sum)

871198282

#23
A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.

A number whose proper divisors are less than the number is called deficient and a number whose proper divisors exceed the number is called abundant.

As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.

In [ ]:
def divisors(number):
  divisors = [1]
  sum = 1
  if number == 1:
    return 1
  count = 2 #1 and itself
  for i in range(2, int(number**.5+1)):
    if number % i == 0:
      sum += i
      if (number // i ) != i:
        sum += number // i
  return sum

abundant = []
for i in range(1, 28123):
  if divisors(i) > i:
    abundant.append(i)

sieve = [True] * 28123

for i in range(len(abundant)):
  for j in range(len(abundant)):
    try:
      sieve[abundant[i]+abundant[j]] = False
    except:
      continue

candidates = [i for i in range(1, len(sieve)) if sieve[i]]

sum = 0
for i in range(len(candidates)):
  sum += candidates[i]

print(sum)

4179871

#24
A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:

012   021   102   120   201   210

What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?

In [63]:
#black magic fuckery

def fact(n):
    f = 1
    #print('fact(n):', n)
    for x in range(1, n+1): 
      #print('f:', f)
      f = f * x
    return f

def permutation(orig_nums, n):
    nums = list(orig_nums)
    perm = []
    while len(nums):
        divider = fact(len(nums)-1)
        pos = n // divider
        #print('pre-calc:')
        #print('divider:', divider)
        #print('n:', n)
        n = n % divider
        #print('\npost-calc:\nn:', n)
        perm.append(nums[pos])
        nums = nums[0:pos] + nums[pos+1:]
        #print('perm:', perm, '\ndivider:', divider, '\npos:', pos, '\nnums:', nums, '\n----------------------------------\n\n\n')
    return perm

#reduce n from 999999 if debug prints are uncommented
perm = permutation(range(0, 10), 999999)
str_ = ''*len(perm)
for i in range(len(perm)):
  str_ = str_+str(perm[i])

print(int(str_))

2783915460