<a href="https://colab.research.google.com/github/CameronKenworthyCode/python/blob/main/project_euler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [ ]:
sum = 0
for i in range(3, 1000):
  if (i % 3 == 0) or (i % 5 == 0):
    sum += i

print(sum)

233168

#2.
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [ ]:
sum = 2
term1 = 1
term2 = 2
term3 = 3
while term3 < 4000000:
  term1 = term2
  term2 = term3
  term3 = term2 + term1
  if term3 % 2 == 0:
    sum += term3

print(sum)

4613732

#3.
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?